name: 'lint, prettify, spellcheck, test, and build'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@v7.0.0
        with:
          node-version-file: .node-version
      - name: enable Yarn 4
        run: corepack enable
      - name: install
        run: yarn install --immutable
      - name: build
        run: yarn build
      - name: run cspell
        run: yarn test:spelling
      - name: run prettier
        run: yarn test:prettier
      - name: run eslint
        run: yarn test:lint
      - name: check changelog
        run: yarn check-changelog
      - name: check copyright headers
        run: yarn check-copyright-headers
      - name: audit dependencies
        run: yarn npm audit --all --recursive --no-deprecations

  test-ubuntu:
    uses: ./.github/workflows/test.yml
    with:
      os: ubuntu-latest
  test-macos:
    uses: ./.github/workflows/test.yml
    with:
      os: macos-latest
  test-windows:
    uses: ./.github/workflows/test.yml
    with:
      os: windows-latest
